export const ROUTER_PATH = {
    REPORTS: '/',
    LOGIN: '/login',
    TASKS: '/tasks',
    USERS: '/users',
    ORDERS: '/orders',
    KNOWLEDGE_BASE: '/knowledge-base',
    NEWS: '/news',
    TRAINING: '/training',
    ANALYTICS: '/analytics',
    SKU: '/sku',
    FAQ: '/faq',
    MAILING: '/mailing',
    FEEDBACK: '/feedback',
    AUTH: '/auth',
};
